from __future__ import annotations
SCHEMAS: dict[str, list[str]] = {
    "students": [
        "student_id",
        "first_name",
        "last_name",
        "full_name",
        "date_of_birth",
        "status",
        "guardian_id",
        "search_rule",
        "notes",
    ],
    "guardians": [
        "guardian_id",
        "guardian_name",
        "email",
        "phone",
        "notes",
    ],
    "classes": [
        "class_id",
        "name",
        "programme_id",
        "calendar_id",
        "day",
        "time",
        "status",
    ],
    "programmes": [
        "programme_id",
        "name",
        "status",
        "notes",
    ],
    "products": [
        "product_id",
        "name",
        "programme_id",
        "status",
    ],
    "programme_products": [
        "programme_product_id",
        "programme_id",
        "product_id",
    ],
    "programme_classes": [
        "programme_class_id",
        "programme_id",
        "class_id",
    ],
    "enrolments": [
        "enrolment_id",
        "student_id",
        "product_id",
        "start_date",
        "end_date",
        "enrolment_status",
    ],
    "attendance": [
        "attendance_id",
        "student_id",
        "class_id",
        "session_date",
        "status",
        "notes",
    ],
    "bank_transactions": [
        "transaction_id",
        "date",
        "description",
        "amount",
        "account",
        "source_file",
        "matched_student_id",
        "matched_guardian_id",
        "match_confidence",
        "match_method",
        "review_status",
        "notes",
    ],
    "payment_aliases": [
        "alias_id",
        "guardian_id",
        "student_id",
        "alias",
        "notes",
    ],
    "payment_allocations": [
        "allocation_id",
        "transaction_id",
        "student_id",
        "amount",
        "allocation_date",
        "notes",
    ],
    "bank_audit": [
        "audit_id",
        "timestamp",
        "action",
        "transaction_id",
        "details",
    ],
}
